// CSS-variable-based color constants for inline styles (responds to light/dark mode)
export const colors = {
  background: 'rgb(var(--color-background))',
  backgroundSecondary: 'rgb(var(--color-background-secondary))',
  surface: 'rgb(var(--color-surface))',
  surfaceHover: 'rgb(var(--color-surface-hover))',
  foreground: 'rgb(var(--color-foreground))',
  foregroundSecondary: 'rgb(var(--color-foreground-secondary))',
  foregroundMuted: 'rgb(var(--color-foreground-muted))',
  accent: 'rgb(var(--color-accent))',
  accentDim: 'rgb(var(--color-accent-dim))',
  danger: 'rgb(var(--color-danger))',
  warning: 'rgb(var(--color-warning))',
  success: 'rgb(var(--color-success))',
  border: 'rgba(var(--color-border) / 0.12)',
  borderActive: 'rgb(var(--color-border-active))',
} as const;

// Static hex terminal theme for XTerm.js (always dark)
export const terminalTheme = {
  background: '#201d1d',
  foreground: '#fdfcfc',
  cursor: '#007aff',
  selectionBackground: 'rgba(0, 122, 255, 0.3)',
  black: '#201d1d',
  red: '#ff3b30',
  green: '#30d158',
  yellow: '#ff9f0a',
  blue: '#007aff',
  magenta: '#cc5de8',
  cyan: '#22b8cf',
  white: '#fdfcfc',
  brightBlack: '#302c2c',
  brightRed: '#d70015',
  brightGreen: '#30d158',
  brightYellow: '#cc7f08',
  brightBlue: '#0056b3',
  brightMagenta: '#cc5de8',
  brightCyan: '#22b8cf',
  brightWhite: '#fdfcfc',
};
