import { describe, expect, it } from "vitest";

import { filterBrowserGeneratedTerminalInput } from "./terminalInputFilter";

describe("filterBrowserGeneratedTerminalInput", () => {
  it("drops secondary device attributes responses generated by the browser terminal", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b[>0;276;0c")).toBe("");
  });

  it("drops primary device attributes responses generated by the browser terminal", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b[?1;2c")).toBe("");
  });

  it("preserves normal user input around filtered terminal responses", () => {
    expect(
      filterBrowserGeneratedTerminalInput("echo ok\x1b[>0;276;0c\r"),
    ).toBe("echo ok\r");
  });

  it("keeps regular control sequences that are not device attribute responses", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b[A")).toBe("\x1b[A");
  });

  it("preserves private CSI sequences that are not device attribute responses", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b[?25l")).toBe(
      "\x1b[?25l",
    );
  });

  it("preserves incomplete device-attribute-like input instead of guessing", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b[>0;276;0")).toBe(
      "\x1b[>0;276;0",
    );
  });

  it("preserves standalone escape key input", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b")).toBe("\x1b");
  });
});
