import { describe, expect, it } from "vitest";

import { filterBrowserGeneratedTerminalInput } from "./terminalInputFilter";

describe("filterBrowserGeneratedTerminalInput", () => {
  it("drops secondary device attributes responses generated by the browser terminal", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b[>0;276;0c")).toBe("");
  });

  it("drops primary device attributes responses generated by the browser terminal", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b[?1;2c")).toBe("");
  });

  it("preserves normal user input around filtered terminal responses", () => {
    expect(
      filterBrowserGeneratedTerminalInput("echo ok\x1b[>0;276;0c\r"),
    ).toBe("echo ok\r");
  });

  it("keeps regular control sequences that are not device attribute responses", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b[A")).toBe("\x1b[A");
  });

  it("preserves private CSI sequences that are not device attribute responses", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b[?25l")).toBe(
      "\x1b[?25l",
    );
  });

  it("preserves incomplete device-attribute-like input instead of guessing", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b[>0;276;0")).toBe(
      "\x1b[>0;276;0",
    );
  });

  it("preserves standalone escape key input", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b")).toBe("\x1b");
  });

  it("drops xterm 6.1 color-scheme DSR responses", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b[?997;1n")).toBe("");
    expect(filterBrowserGeneratedTerminalInput("\x1b[?997;2n")).toBe("");
  });

  it("drops XTVERSION DCS responses", () => {
    expect(
      filterBrowserGeneratedTerminalInput("\x1bP>|xterm.js(6.1.0-beta.303)\x1b\\"),
    ).toBe("");
  });

  it("drops window-ops pixel and cell reports", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b[4;720;1280t")).toBe("");
    expect(filterBrowserGeneratedTerminalInput("\x1b[6;17;8t")).toBe("");
    expect(filterBrowserGeneratedTerminalInput("\x1b[8;24;80t")).toBe("");
  });

  it("drops focus in/out reports", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b[I")).toBe("");
    expect(filterBrowserGeneratedTerminalInput("\x1b[O")).toBe("");
  });

  it("preserves cursor-key input that is not a focus report", () => {
    expect(filterBrowserGeneratedTerminalInput("\x1b[A")).toBe("\x1b[A");
  });
});
